[common]
meta = 0_01_z_0_5_4_0_snr_inf

[directories]
user = /home/elom
work = ${user}/autoencoders

train = ${user}/spectra/${common:meta}
save_model_to = ${train}

[files]
train = test_spectra.npy
save_reconstruction = False

[architecture]
encoder = 256_128_54
latent_dimensions = 12
decoder = 54_128_256
is_variational = True
model_name = infoVae
verbose = 1

[hyperparameters]
validation_split = 0.2
learning_rate = 0.001
batch_size = 256
epochs = 10
output_activation = linear
verbose_learning_rate = 1
verbose_early_stop = 1
# L = MSE + (1-alpha)* KLD + (alpha + lambda -1) MDD

# weights
reconstruction_weight = 3776
mmd_weight = 1
kld_weight = 1

# loss parameters
alpha = 0
lambda = 8.606942414688938

# training parameters
early_stop_patience = 10
learning_rate_patience = 5
workers = 48
use_multiprocessing = True

seed = 123

[tensorflow-session]
cores = 1
